version: '3.8'
name: slipstream

services:
  app:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
    ports:
      - "5173:5173"
    volumes:
#      - ./deploy/s6-overlay/scripts/runas-user:/etc/s6-overlay/scripts/runas-user
      - ./deploy/s6-overlay/scripts/laravel-automations:/etc/s6-overlay/scripts/laravel-automations
#      - ./deploy/nginx/sites-enabled/websockets.conf:/etc/nginx/sites-enabled/websockets.conf
      - ./:/var/www/html
    environment:
      PUID: 1000
      PGID: 1000
    #            - ./.env:/var/www/html/.env # .env File
    #            - ./teststorage/app:/var/www/html/storage/app # App folder
    #            - ./teststorage/logs:/var/www/html/storage/logs # Logs
