version: '3.8'
name: slipstream

services:
    app:
        container_name: Slipstream
        image: slipstream:latest
        build:
            context: ./
            dockerfile: ./deploy/Dockerfile
        ports:
            - 80:80
        depends_on:
            - db
        environment:
            PUID: 1000
            PGID: 1000
#            DB_HOST: slipstream-db
#            DB_PASSWORD: yoursecretdbpass
        volumes:
            - ./:/var/www/html
        #            - ./.env:/var/www/html/.env # .env File
        #            - ./teststorage/app:/var/www/html/storage/app # App folder
        #            - ./teststorage/logs:/var/www/html/storage/logs # Logs
        networks:
            - slipstream_network

    db:
        image: mysql:8
        container_name: slipstream-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: slipstream
            MYSQL_ROOT_PASSWORD: yoursecretdbpass
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - slipstream_network

volumes:
    dbdata:

networks:
    slipstream_network:
        driver: bridge
