version: '3.8'
name: slipstream

services:
    app:
        container_name: Slipstream
        image: slipstream:latest
        ports:
            - 80:80
        volumes:
            - ./data:/var/www/html/data
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_HOST: slipstream-db
            DB_DATABASE: slipstream
            DB_USERNAME: root
            DB_PASSWORD: yoursecretdbpass
        networks:
            - slipstream_network

    db:
        image: mysql:8
        container_name: slipstream-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: slipstream
            MYSQL_ROOT_PASSWORD: yoursecretdbpass
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - slipstream_network
        healthcheck:
            test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
            interval: 3s
            timeout: 20s
            retries: 30

volumes:
    dbdata:

networks:
    slipstream_network:
        driver: bridge

