#!/command/with-contenv bash

PUID=${PUID:-9999}
PGID=${PGID:-9999}
WEBUSER_HOME=${WEBUSER_HOME:-"/var/www/html"}

if [[ $PUID != 9999 || $PGID != 9999 ]]; then

    # Change the group ID
    groupmod -o -g "$PGID" webgroup

    # Change the User ID
    usermod -o -u "$PUID" webuser

    # Make sure the home directory is updated with the proper UID & GID
    chown webuser:webgroup $WEBUSER_HOME
fi

if [[ $S6_LOGGING != 1 ]]; then

echo '
--------------------------------------------------------------------

 _______ __ __               __
|     __|  |__|.-----.-----.|  |_.----.-----.---.-.--------.
|__     |  |  ||  _  |__ --||   _|   _|  -__|  _  |        |
|_______|__|__||   __|_____||____|__| |_____|___._|__|__|__|
               |__|


Docker base image by https://serversideup.net
Slipstream by Chris Toxz (https://github.com/ChrisToxz)
--------------------------------------------------------------------'

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u webuser)
User gid:    $(id -g webuser)
-------------------------------------
"
fi
